### ISSUE TITLE
getting basic issues with import

### ISSUE THREAD

**Issue by atanudasgupta** [natter1/python_pptx_interface#8]
any idea, why am I getting these problems.

{
	"name": "ImportError",
	"message": "cannot import name 'EnumValue' from 'pptx.enum.base' (/Users/atanudasgupta/miniconda3/envs/python_312/lib/python3.12/site-packages/pptx/enum/base.py)",
	"stack": "---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 18
     14 import os
     16 from pptx.util import Inches
---> 18 from pptx_tools.creator import PPTXCreator
     19 from pptx_tools.paragraph_style import PPTXParagraphStyle
     20 from pptx_tools.position import PPTXPosition

File ~/miniconda3/envs/python_312/lib/python3.12/site-packages/pptx_tools/creator.py:12
     10 from pptx_tools import utils
     11 from pptx_tools.position import PPTXPosition
---> 12 from pptx_tools.table_style import PPTXTableStyle
     14 try:
     15     from matplotlib.figure import Figure

File ~/miniconda3/envs/python_312/lib/python3.12/site-packages/pptx_tools/table_style.py:11
      8 from pptx.table import Table, _Cell
      9 from pptx.util import Inches
---> 11 from pptx_tools.font_style import PPTXFontStyle
     12 from pptx_tools.position import PPTXPosition
     13 from pptx_tools.fill_style import PPTXFillStyle

File ~/miniconda3/envs/python_312/lib/python3.12/site-packages/pptx_tools/font_style.py:17
     14 from pptx.util import Pt
     16 from pptx_tools.enumerations import TEXT_CAPS_VALUES, TEXT_STRIKE_VALUES
---> 17 from pptx_tools.fill_style import PPTXFillStyle
     18 from pptx_tools.utils import _USE_DEFAULT, _DO_NOT_CHANGE
     21 class PPTXFontStyle:

File ~/miniconda3/envs/python_312/lib/python3.12/site-packages/pptx_tools/fill_style.py:10
      8 from pptx.dml.color import RGBColor
      9 from pptx.dml.fill import FillFormat
---> 10 from pptx.enum.base import EnumValue
     11 from pptx.enum.dml import MSO_THEME_COLOR_INDEX
     12 from pptx.enum.dml import MSO_PATTERN_TYPE

ImportError: cannot import name 'EnumValue' from 'pptx.enum.base' 
}

**Comment by natter1** [comment]
Hmm, I haven't checked with a new install for a while. My guess would be some change with a recent update of pptx. I will have a look into it, but it might take a while.

**Comment by natter1** [comment]
As expected, some things were changed in python-pptx. The next release will work with python-pptx 1.0.0.
